locale                   : "en-US"
title                    : "Harin Lee"
title_separator          : "-"
name                     : &name "Harin Lee"
description              : &description "People Analytics | Human-AI Collaboration | Industrial Engineering"
url                      : "https://daisy-blossom-v.github.io"
baseurl                  : ""
repository               : "daisy-blossom-v/daisy-blossom-v.github.io"

author:
  name             : "Harin Lee"
  avatar           : "profile.jpg"
  bio              : "PhD Applicant · People Analytics · Human-AI Collaboration · Industrial Engineering"
  location         : "Seoul, Republic of Korea"
  email            : "harinlee0503@gmail.com"
  github           : "daisy-blossom-v"
  linkedin         :
  googlescholar    :
  orcid            :
  researchgate     :

include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .github
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: false
      related: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: false
      comments: false
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: false
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: false
      comments: false

sass:
  sass_dir: _sass
  style: compressed

permalink: /:categories/:title/
timezone: Asia/Seoul

plugins:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

compress_html:
  clippings: all
  ignore:
    envs: development
